dist: xenial

addons:
 snaps:
   - hugo

sudo: true

branches:
  only:
    - master
    - source

env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="source"
    - DEPLOY_BRANCH="master"

script:
  - hugo

deploy:
  - provider: pages
    edge: true
    github_token: ${GITHUB_TOKEN}
    fqdn: dev.usable.tools
    local_dir: public
    skip_cleanup: true
    target_branch: master
    on:
      branch: source
