# 
# ------------------
# Travis seemed to be necessary for legacy builds, but no longer
# As such, I commented it out in favour of the standard GitHub build action for Hugo
# Builds don't seem to throw any errors with travis.yml commented out, but kept the code here
#   just in case something breaks once
# ------------------
#

# dist: xenial

# addons:
#  snaps:
#    - hugo

# sudo: true

# branches:
#   only:
#     - master
#     - source

# env:
#   global:
#     - SOURCE_DIR="public"
#     - BUILD_BRANCH="source"
#     - DEPLOY_BRANCH="master"

# script:
#   - hugo

# deploy:
#   - provider: pages
# #    edge: true
#     github_token: ${GITHUB_TOKEN}
#     fqdn: usable.tools
#     local_dir: public
#     skip_cleanup: true
#     target_branch: master
#     on:
#       branch: source
